---
- name: network management
  block:
    - name: get network facts
      community.libvirt.virt_net:
        command: facts
      changed_when: False

    - name: define network
      community.libvirt.virt_net:
        command: define
        name: "{{ item.name }}"
        xml: "{{ lookup('template', 'network.xml.j2') }}"
      when: "item.name not in ansible_libvirt_networks"
      loop: "{{ libvirt.net }}"

    - name: start the network
      community.libvirt.virt_net:
        name: "{{ item.name }}"
        state: active
      loop: "{{ libvirt.net }}"

    - name: autostart network
      community.libvirt.virt_net:
        name: "{{ item.name }}"
        autostart: True
      when: item.autostart
      loop: "{{ libvirt.net }}"
